### ISSUE TITLE
非常好的模块，但是我遇到一些问题，希望解惑

### ISSUE THREAD

**Issue by EscapeA** [weixiansen574/AlarmShell#2]
我使用的是
 hyperOS23.11.8+kernelSU 0.7.1 +LSPosed 1.9.2
我确认闹钟备注和脚本文件名一致
同时kernelSU为闹钟授予了root
我在脚本中写了 
`sleep 2
input swipe 500 1500 500 500
#上滑关闭闹钟，执行正常

sleep 2
input swipe 500 1500 500 500
#解锁屏幕，通过近距离蓝牙手环直接滑动解锁，执行正常

sleep 1

echo "success" >> test.txt
#似乎未执行，未生成文件test.txt

/data/user/0/com.termux/files/usr/bin/python ./test/test.py
#似乎未执行

sleep 30
input keyevent KEYCODE_POWER
#关闭屏幕,执行正常`

中间两行似乎没有执行，但是直接使用MT管理器执行一切正常，是有一些其他的原因吗,希望有大佬解惑，感谢

**Comment by weixiansen574** [comment]
我也在用termux
```
echo "success" >> test.txt
#似乎未执行，未生成文件test.txt
```
首先这段代码是存在问题的，如果你未指定test.txt的路径，它会放到根目录下，而非脚本的相对路径   
要输出日志，您可以放在内部存储目录`/storage/emulated/0/test.txt`下  
再者，你用的是termux里的Python，可能因环境问题无法执行  
你需要用termux执行特定命令，可以换一个思路：am命令启动termux，然后模拟输入向termux执行命令
``` sh
sleep 1
am start -n com.termux/main.java.com.termux.app.TermuxActivity2
sleep 5
input text "tsu
"
sleep 1
input text "python
"
```

**Comment by EscapeA** [comment]
> 能否提供一下lsp日志？ 找到“AlarmShell:”开头的就可以了，这是脚本执行的输出

[ 2023-11-20T21:01:00.668    10240: 25314: 25314 I/LSPosed-Bridge  ] 2023-11-20 21:01:00 正在执行shell脚本:/data/user/0/com.android.deskclock/files/shell/test.sh
[ 2023-11-20T21:01:00.896    10240: 25314:  5869 I/LSPosed-Bridge  ] 2023-11-20 21:01:00 shell脚本执行结束：/data/user/0/com.android.deskclock/files/shell/test.sh

**Comment by EscapeA** [comment]
> 我也在用termux
> 
> ```
> echo "success" >> test.txt
> #似乎未执行，未生成文件test.txt
> ```
> 
> 首先这段代码是存在问题的，如果你未指定test.txt的路径，它会放到根目录下，而非脚本的相对路径 要输出日志，您可以放在内部存储目录`/storage/emulated/0/test.txt`下 再者，你用的是termux里的Python，可能因环境问题无法执行 你需要用termux执行特定命令，可以换一个思路：am命令启动termux，然后模拟输入向termux执行命令
> 
> ```shell
> sleep 1
> am start -n com.termux/main.java.com.termux.app.TermuxActivity2
> sleep 5
> input text "tsu
> "
> sleep 1
> input text "python
> "
> ```

好的，我试试，感谢

**Comment by EscapeA** [comment]
> > 我也在用termux
> > ```
> > echo "success" >> test.txt
> > #似乎未执行，未生成文件test.txt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 首先这段代码是存在问题的，如果你未指定test.txt的路径，它会放到根目录下，而非脚本的相对路径 要输出日志，您可以放在内部存储目录`/storage/emulated/0/test.txt`下 再者，你用的是termux里的Python，可能因环境问题无法执行 你需要用termux执行特定命令，可以换一个思路：am命令启动termux，然后模拟输入向termux执行命令
> > ```shell
> > sleep 1
> > am start -n com.termux/main.java.com.termux.app.TermuxActivity2
> > sleep 5
> > input text "tsu
> > "
> > sleep 1
> > input text "python
> > "
> > ```
> 
> 好的，我试试，感谢

完美运行，非常感谢指导
