### ISSUE TITLE
[Feature-Request] Auto turn off alarm

### ISSUE THREAD

**Issue by Webpage-gh** [weixiansen574/AlarmShell#4]
您好，这个模块的想法很棒。既然hook系统闹钟了，能不能直接自动关掉这个闹钟？模拟滑动来关闭闹钟似乎更耗费时间

**Comment by AABBDFGZXZ** [comment]
#可以这样试试，这里要睡眠一段时间主要是等屏幕出现闹钟提醒的画面，如果不睡眠直接kill闹钟的话好像有点问题
sleep 2
am force-stop com.android.deskclock
#解锁屏幕
input swipe 500 1900 500 1000 && input text 123456 && input keyevent 66
#解锁后的操作
...
